### ISSUE TITLE
Rename Repository and Composer Package

### ISSUE THREAD

**Issue by bshaffer** [googleapis/gax-php#144]
As the term "GAX" is a bit arcane, we should rename the repository and package. One option is as follows:

 * Repo: `googleapis/gax-php` => `googleapis/php-core` 
 * Package: `google/gax` => `google/api-core`.

Because other repositories are using "common"  (e.g. `api-common-java` and `nodejs-common`), and also because we have other namespaces besides `ApiCore` in `google/gax`, we should consider the following as well:

 * Repo: `googleapis/gax-php` => `googleapis/php-common` 
 * Package: `google/gax` => `google/api-common`.

Thoughts?

**Comment by bshaffer** [comment]
cc @michaelbausor @dwsupplee

**Comment by dwsupplee** [comment]
There's a lot of value in consistency with the other languages. Makes me lean towards `api-common` :)

**Comment by bshaffer** [comment]
It should be mentioned python has a library called [`api_core`](https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/api_core), so full consistency cannot be achieved 😄  

I am also leaning towards common, because of the consistency and because `ApiCore` is only one of several namespaces in this package.

**Comment by vchudnov-g** [comment]
@michaelbausor Any updates on this? Is this properly prioritized?

**Comment by michaelbausor** [comment]
I think that this can perhaps be closed. There is not a push to move away from "gax" across languages, so sticking with gax as repo and package name is acceptable. @dwsupplee @bshaffer please reopen the issue and the discussion if you disagree.
