### ISSUE TITLE
Better RequestBuilder Error Message

### ISSUE THREAD

**Issue by bshaffer** [googleapis/gax-php#152]
In `RequestBuilder`, the error message is `Failed to build the provided path (google.cloud.iot.v1.DeviceManager/ListDevices) with the supplied message.` when anything goes wrong.

This error message is not very useful for debugging. The case I ran into is the `projectId` was empty in a template with format `projects/{projectId}'. This took a while to debug.

A better error message would propagate the errant value somewhere in the exception. Something like `Invalid "parent" attribute for google.cloud.iot.v1.DeviceManager/ListDevices`.

**Comment by michaelbausor** [comment]
Fixed in https://github.com/googleapis/gax-php/pull/154
