### ISSUE TITLE
Make PagedListResponse Iterable

### ISSUE THREAD

**Issue by bshaffer** [googleapis/gax-php#153]
We should make `PagedListResponse` iterable. This would clean up the code:

```php
$devices = $client->getDevices($parent, $registry);

// current code, not intuitive
foreach ($devices->iterateAllElements() as $device) {
    printf('Device ID: %s' . PHP_EOL, $device->getId());
}

// better code
foreach ($devices as $device) {
    printf('Device ID: %s' . PHP_EOL, $device->getId());
}
```

Another issue is the second one does not throw an error, it just fails to print out anything, which is the same behavior as if it had no elements. So it's very confusing!

**Comment by michaelbausor** [comment]
Making a note here: this feature should also include updating codegen method samples to use direct iteration syntax.

**Comment by sirtorry** [comment]
bump

**Comment by bshaffer** [comment]
This would be a really great feature for GAX GA!

**Comment by michaelbausor** [comment]
I have one concern about this feature, which is whether users will know that when they write:
```php
foreach ($devices as $device) {
    printf('Device ID: %s' . PHP_EOL, $device->getId());
}
```
that this may actually invoke multiple RPCs. That is the motivation behind explicitly requiring users to call `iterateAllElements()`.

But, I am open to the idea that this is wrong, and we should prefer the usability. Thoughts?

**Comment by jdpedrie** [comment]
Google Cloud PHP will iterate through pages in the proposed manner, and I'm not sure that the name `iterateAllElements()` necessarily implies the underlying process of automatic pagination anyways (perhaps `iteratePagedElements()` or something would better convey that).

It may be that we should do better in general of informing users of the implications of an unbounded foreach over our iterators, but I think the usability and semantic benefits outweigh the other concerns.

One also would hope that the name of the class should offer some information as to the behavior. :)

**Comment by michaelbausor** [comment]
Sounds good guys - I'll open a PR soon.
