### ISSUE TITLE
Improper Parsing of FieldMask for REST requests

### ISSUE THREAD

**Issue by bshaffer** [googleapis/gax-php#155]
Same as https://github.com/GoogleCloudPlatform/google-cloud-php/issues/958

Field Masks are being improperly parsed as querystrings due to the fact they are handled in a special way by `serializeToJsonString`.  For example, for the following `FieldMask`:

```php
$mask = new FieldMask;
$mask->setPaths(['credentials']);
```

`FieldMask::getQuerystringValue` returns a string, but `RequestBuilder` [expects an array](https://github.com/googleapis/gax-php/blob/df3af58e5f9b29c8126b1191f4b413e13e4eb468/src/ApiCore/RequestBuilder.php#L124). As a result, nothing is rendered, when the correct way to parse it is `update_mask.paths=credentials`. 

When the `FieldMask` is parsed like any other message, this issue goes away. So one possible fix would be for the RequestBuilder to exclude `FieldMask` specifically when calling [`messageToArray`](https://github.com/googleapis/gax-php/blob/master/src/ApiCore/RequestBuilder.php#L222):

```php
if (GPBUtil::hasSpecialJsonMapping($message) && !$message instanceof FieldMask) {
    return json_decode($message->serializeToJsonString(), true);
}
$messageArray = [];
foreach ($this->getAllProperties($message) as $name => $value) {
    $propertyValue = $this->getPrivatePropertyValue($message, $name);
    $messageArray[$name] = $this->getQuerystringValue($propertyValue);
}
return $messageArray;
```

**Comment by michaelbausor** [comment]
I will look at fixing - can you share an example API call you used to find/test this?

**Comment by bshaffer** [comment]
I can submit a fix. I think the best way to do it is to call a local private method instead of using `GPBUtil`, since this is causing https://github.com/GoogleCloudPlatform/google-cloud-php/issues/957

**Comment by michaelbausor** [comment]
Fixed in https://github.com/googleapis/gax-php/pull/156
