### ISSUE TITLE
Unexpected error in GAX JISON parser for Firestore document path.

### ISSUE THREAD

**Issue by jdpedrie** [googleapis/gax-php#197]
See googlecloudplatform/google-cloud-php#1119 for context.

The parse methods in GAX do not accept various symbols which are valid values in Firestore document names.

`*`
`=`
`}`
`{`

The presence of any of these symbols in arguments given to `FirestoreGapicClient::documentPathName()` raises the following error:

```
Fatal error: Uncaught Exception: Parse error on line 1:
Kind/F{[<,>.?509880146
------^
Expecting FORWARD_SLASH, COLON, RIGHT_BRACE, got 'LEFT_BRACE'
```

Is there any possibility that the parser may be able to support these symbols?

**Comment by michaelbausor** [comment]
Closing this since support was released in gax 0.37. If there are still issues once google-cloud-php moves to 0.37, please feel free to reopen.
