### ISSUE TITLE
GAX Parser empty/falsey value throws cryptic exception.

### ISSUE THREAD

**Issue by jdpedrie** [googleapis/gax-php#214]
The old JISON parser accepted various values evaluating to `''` for template placeholders. The replacement parser released in v0.37.0 doesn't support empty values.

This strikes me as a good thing, since resource names missing (for instance) a project ID aren't valid, however the error message arising from this case is a bit hard to understand for new users. (see https://github.com/GoogleCloudPlatform/google-cloud-php/issues/1276).

Current behavior:

```php
echo FirestoreGapicClient::databaseRootName(null, '(default)');
// Uncaught Google\ApiCore\ValidationException: Cannot bind segment '{project=*}' to value ''
```

Improved behavior:

```php
echo FirestoreGapicClient::databaseRootName(null, '(default)');
// Uncaught Google\ApiCore\ValidationException: Segment '{project=*}' expected non-empty string, instead got null.
```

**Comment by michaelbausor** [comment]
Opened https://github.com/googleapis/gax-php/pull/215 to address this, PTAL
