### ISSUE TITLE
Warning in gax/version - file not found

### ISSUE THREAD

**Issue by dmachehin** [googleapis/gax-php#243]
Source file:line /home/xxx/xxx/vendor/google/gax/src/Version.php:59
Msg: file_get_contents(/home/xxx/xxx/vendor/googleads/google-ads-php/VERSION): failed to open stream: No such file or directory

#### Environment details

  - OS: CentOS 6
  - PHP version: 7.2.19
  - Package name and version: googleads/google-ads-php: 1.4.1

#### Steps to reproduce

  1. Use composer.json and require package `googleads/google-ads-php: 1.4.1`
  2. Run example code and see notice

#### Code example

```php
<?php
require_once __DIR__.'/vendor/autoload.php';

set_error_handler(function ($num, $msg, $file, $line, $ctx) {
	echo "Error ({$num}) occurred in {$file}:{$line} - {$msg}"."\n";
}, error_reporting());

$oauth_credential = new \Google\Auth\FetchAuthTokenCache(
	new \Google\Auth\Credentials\UserRefreshCredentials('https://www.googleapis.com/auth/adwords', [
		'client_id' => 123,
		'client_secret' => 123,
		'refresh_token' => 123
	]),
	null,
	new \Google\Auth\Cache\MemoryCacheItemPool
);

$client = (new \Google\Ads\GoogleAds\Lib\V1\GoogleAdsClientBuilder())
	->withDeveloperToken(123)
	->withOAuth2Credential($oauth_credential)
	->build();

$client->getAccountBudgetServiceClient();
```

Related issue in google-ads-php repo: https://github.com/googleads/google-ads-php/issues/136

**Comment by dwsupplee** [comment]
We just released a patch: https://github.com/googleapis/gax-php/releases/tag/0.38.2
