### ISSUE TITLE
Add Caching for Auth Token Fetching

### ISSUE THREAD

**Issue by bshaffer** [googleapis/gax-php#26]
In [createCallCredentialsCallback](https://github.com/googleapis/gax-php/blob/master/src/GrpcBootstrap.php#L54), the fetching of access tokens happens upon each GRPC request.

We need to add caching to this function. This can be done in some naive way, or by using the [CacheTrait](https://github.com/google/google-auth-library-php/blob/master/src/CacheTrait.php) included in the Auth library.

**Comment by dwsupplee** [comment]
/cc @garrettjonesgoogle @jgeewax

This is something we will definitely need fixed before being able to move forward with merging in any code in gcloud-php. I am happy to take a stab at this, just let me know what the plan is.

**Comment by bshaffer** [comment]
Added caching class in https://github.com/google/google-auth-library-php/issues/123

**Comment by michaelbausor** [comment]
Closing out old issues. Auth caching is available in auth library and used by clients.
