### ISSUE TITLE
Add Protobuf info in the agent header "x-goog-api-client"

### ISSUE THREAD

**Issue by PierrickVoulet** [googleapis/gax-php#262]
**Is your feature request related to a problem? Please describe.**

A basic value currently looks like `gl-php/7.2.16-1+ubuntu14.04.1+deb.sury.org+1 gapic/ gax/1.2.0 grpc/1.26.0`. Two additional pieces of information would be great to add:

- Version of Protobuf
- Protobuf implementation (C or PHP)

 **Describe the solution you'd like**

Improve the agent header value to contain the protobuf information in the following format: `protobuf-<implementation type>/<version>`

- `<version>`: `3.11.4` for example
- `<implementation>`: `c` for the C implementation (extension) or `php` for the PHP implementation (regular dependency)

For example: `gl-php/7.2.16-1+ubuntu14.04.1+deb.sury.org+1 gapic/ gax/1.2.0 grpc/1.26.0 protobuf-c/3.11.4`

 **Additional context**

This is really helpful for troubleshooting issues (based on basic logging)

**Comment by PierrickVoulet** [comment]
@hkdevandla friendly ping. Is there anything I can do to help you make this move forward?

**Comment by bshaffer** [comment]
This has been added in https://github.com/googleapis/gax-php/pull/387
