### ISSUE TITLE
configureCallConstructionOptions does not respect phpDocComment type

### ISSUE THREAD

**Issue by ivanrey** [googleapis/gax-php#269]
In [GapicClientTrait::configureCallConstructionOptions](https://github.com/googleapis/gax-php/blob/5867739a1db253b4cd64b0856c292598d271fd8d/src/GapicClientTrait.php#L511), the documentation states that `$retrySettings` should be of type `RetrySettings`. However, in [configureCallConstructionOptions] (https://github.com/googleapis/gax-php/blob/5867739a1db253b4cd64b0856c292598d271fd8d/src/GapicClientTrait.php#L522) it uses the `$retrySettings` as an argument for the [RetrySettings::width](https://github.com/googleapis/gax-php/blob/831643d2e765c773924507025f0f2f204f680f3d/src/RetrySettings.php#L335) which only accepts `array` as arguments. Thus if one sends a `RetrySettings` object as stated in multiple parts of the documentation for the `$optionalArgs['retrySettings]` key, then an error is rased stating `Uncaught Type Error argument 1 must be of type array, object given`

**Comment by hkdevandla** [comment]
@vam-google @miraleung , can you please take a look?

**Comment by dwsupplee** [comment]
Nice find, and thanks for the report @ivanrey. I've opened https://github.com/googleapis/gax-php/pull/270 to address this.
