### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dwsupplee** [googleapis/gax-php#27]
Hi guys,

Would we be able to tag a new release which includes updated auth and gRPC dependencies?

**Comment by dwsupplee** [comment]
https://github.com/google/google-auth-library-php/issues/121

It sounds like another BC break for auth may be on the way in which case it would probably be best to wait for that.

**Comment by michaelbausor** [comment]
I will tag a new release once https://github.com/google/google-auth-library-php/pull/123 is merged
