### ISSUE TITLE
Composer warning!

### ISSUE THREAD

**Issue by gentritabazi01** [googleapis/gax-php#274]
```Deprecation Notice: Class GPBMetadata\Google\ApiCore\Tests\Unit\Example located in ./vendor/google/gax/metadata/Google/ApiCore/Tests/Unit/Example.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.10.1/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201```

**Comment by dwsupplee** [comment]
Similar issue: https://github.com/googleapis/gax-php/issues/264
