### ISSUE TITLE
Timestamp type appears to be missing

### ISSUE THREAD

**Issue by dwsupplee** [googleapis/gax-php#28]
When attempting to decode a message received from pubsub I'm getting the following error:

`PHP Fatal error:  Class '\google\protobuf\Timestamp' not found in /Users/dave/dev/gcloud-php/vendor/stanley-cheung/protobuf-php/library/DrSlump/Protobuf/Codec/Binary.php on line 267`

I looked through `src/generated` and wasn't able to find this type. 

Please let me know if there is anything I can do to help.

**Comment by michaelbausor** [comment]
This fixed the issue in my tests, please let me know if you are still seeing a  problem
