### ISSUE TITLE
Bump protobuf version to 3.15

### ISSUE THREAD

**Issue by blodan** [googleapis/gax-php#316]
#### Problem description

Missmatch between protobuf versions causes this error;
```exception: "ErrorException"
message: "proto descriptor was previously loaded (included in multiple metadata bundles?)"
```

From my digging I understand that trying to use the PHP pecl module of protobuf at the same time as a composer package utilizing another version of protobuf causes this error.

We are currenlty using the googleads/google-ads-php package which wants protobuf 3.15 while gax-php wants protobuf 3.12. 

While having the protobuf php module enabled the above error gets triggered, but when only using the different version composer packages of protobuf it does not get triggered.

So the request here is if you could bump your protobuf dependency to 3.15 to match googleads/google-ads-php so that we can use the php pecl module for protobuf

#### Environment details

  - OS: Docker php:8.0.3-fpm-alpine
  - PHP version: 8.0
  - Package name and version: 

#### Steps to reproduce

  1. Install protobuf 3.15.* php module
  2. php composer.phar require googleads/google-ads-php
  3. Try to fetch data that triggers gax-php

**Comment by dwsupplee** [comment]
Hi @blodan 👋, we require 3.12 at a minimum, not specifically. If you upgrade your dependencies it should install the latest (3.15) for you. Have you found otherwise?

**Comment by blodan** [comment]
Hi @dwsupplee,

Thanks for the tip!
I forked the package and bumped the depency but that didn't solve the problem.

Sorry for making the wrong conclusion, the problem isn't with gax-php
