### ISSUE TITLE
GAX Error - Could not construct ApplicationDefaultCredentials 

### ISSUE THREAD

**Issue by SubaKrishnan** [googleapis/gax-php#340]
#### Environment details

  - OS: Windows 10
  - PHP version: 7.3.28
  - Package name and version: google-ads-php v11.0.0

#### Steps to reproduce

  Upgrading google-ads-php from version 6 to version 11, shouts Error.

**Error**
  ```
Google\ApiCore\ValidationException
  Could not construct ApplicationDefaultCredentials From gax
``` 

  Previously I'm using google-ads-php v6.0.0. I got error as Version v6 is deprecated. Therefore, I updraged to the current version v11.0.0 where I'm getting Error from gax. 

  Help me to sort this issue. Thanks in advance

**Comment by hkdevandla** [comment]
@noahdietz , can you please triage this? Thanks!

**Comment by noahdietz** [comment]
@pierrickvoulet could you help us triage what has changed between v6 and v11 of the google-ads-php library?

**Comment by PierrickVoulet** [comment]
@noahdietz The only related change that I can find is that we bumped the minimal version of `gax-php` from `^1.5.0` to `^1.7.0`. We did not change anything in the authentication logic as far as I know.

@hkdevandla Do you know by any chance what version of `gax-php` you were using before upgrading `google-ads-php` to `11.0.0`?

**Comment by noahdietz** [comment]
Thanks @PierrickVoulet that helps.

> Do you know by any chance what versions of `gax-php` you were using before upgrading `google-ads-php` to `11.0.0` and after upgrading?

@SubaKrishnan can you answer this?

**Comment by SubaKrishnan** [comment]
Sorry for the delay, Earlier I used gax-php V1.6 After Updating to v1.7 I received this error.

I fixed this issue. In Laravel Application, $clientOptions variable which passes the credentials doesn't return any value. Because Oauth hadn't been recognized properly in AppServiceProvider. Now, It works fine.

Thanks guys

**Comment by SubaKrishnan** [comment]
Sure..Thanks for your time
