### ISSUE TITLE
PHP 8.1 Deprecation

### ISSUE THREAD

**Issue by exstreme** [googleapis/gax-php#381]
#### Environment details

  - OS: don't care
  - PHP version:8.1

PHP Deprecated:  Return type of Google\ApiCore\Page::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/google/gax/src/Page.php on line 173
PHP Deprecated:  Return type of Google\ApiCore\PagedListResponse::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/google/gax/src/PagedListResponse.php on line 124

**Comment by noahdietz** [comment]
@exstreme can you please clarify exactly what you would like to see happen? It is not clear to me.

**Comment by exstreme** [comment]
@noahdietz If you implements any class (by example IteratorAggregate) you should have compatible return types for all implemented methods (https://www.php.net/manual/en/iteratoraggregate.getiterator.php [Traversable] for getIterator).
Since 8.1 it returns deprecation errors.
But there are 2 solutions for this case:
1) By adding return type, but it is working only with PHP 7.4 and higher
2) By adding #[\ReturnTypeWillChange] attribute

**Comment by bshaffer** [comment]
fixed in #378 and v1.12.2
