### ISSUE TITLE
how can i config auth http handler for  CredentialsWrapper and how to make it become effective.

### ISSUE THREAD

**Issue by hhniao** [googleapis/gax-php#458]
when i cant access googleapis, i need proxy for it.
in this file vendor/google/gax/src/CredentialsWrapper.php:212
`return $credentialsFetcher->updateMetadata([], $audience);`
i need change it to:
`return $credentialsFetcher->updateMetadata([], $audience, $authHttpHandler);`

\Google\Ads\GoogleAds\Lib\V13\GoogleAdsClient it is a final class, 
i cant extend it, so i copy this file and change it
maybe any other way to do this ?
```php
class GoogleAdsClient extends \Google\Ads\GoogleAds\Lib\V13\GoogleAdsClient {
    public function getGoogleAdsClientOptions(): array
    {
      $options = parent::getGoogleAdsClientOptions();
      $handler = HttpHandlerFactory::build(new Client([
          'proxy'   => config('google.proxy'),
          'timeout' => 5,
      ]));
      $options['credentialsConfig'] = ['authHttpHandler' => $handler];
      return $options;
   }
}
```

**Comment by bshaffer** [comment]
This is a great question!

In the generated API clients (in Ads, this is anything in the `Services` namespace), we have included a way to pass the proxy class down to the transport layer! 

These options can also be passed in when you create the clients, but as `GoogleAdsClient` does not (to my knowledge) have any way to pass this configuration down, you have to create them directly. So for instance if you're using the `BatchJobServiceGapicClient`, you could do something like this:

```php
use Google\Ads\GoogleAds\Lib\V13\Services\BatchJobServiceGapicClient;
use Google\Auth\HttpHandler\ HttpHandlerFactory;
use GuzzleHttp\Client;

// create your custom HTTP handler
$httpHandler = HttpHandlerFactory::build(new Client([
    'proxy'   => config('google.proxy'),
    'timeout' => 5,
]));

// Pass the `httpHandler` into the client constructor:
$batchJobClient = new BatchJobServiceGapicClient([
    // Configure the httpHandler for calls to fetch an auth token
    'credentialsConfig' => ['authHttpHandler' => $httpHander],

    // Configure the httpHandler for each RPC calls
    // (NOTE: this only applies if the REST transport is used instead of gRPC)
    'transportConfig' => ['rest' => ['httpHandler' => $httpHandler]],
]);

$batchJobClient->listBatchJobResults($resourceName);
```

If you only want to pass request options in for the RPC call (and not for the auth call), you can do something like this (for REST requests):

```php
use Google\Ads\GoogleAds\Lib\V13\GoogleAdsClient;
use GuzzleHttp\Client;

$adsClient = new GoogleAdsClient();

// Pass HTTP options directly to the guzzle client at request-time:
$batchJobClient = $adsClient->getBatchJobServiceClient();
$batchJobClient->listBatchJobResults($resourceName, [
    'restOptions' => [
        'proxy'   => config('google.proxy'),
        'timeout' => 5,
    ],
    // you can also pass in grpc options if you're using grpc!
    // 'grpcOptions' => [ /* ... */],
]);
```

We are trying to make all these options better documented by implementing [Options classes](https://github.com/googleapis/gax-php/pull/450), but the Ads clients (specifically, `GoogleAdsClient`) works differently, so you may be better off requesting this as a feature over at https://github.com/googleads/google-ads-php

**Comment by hhniao** [comment]
@bshaffer thanks for you answer. 
i have change request to rest api, not use grpc.

**Comment by bshaffer** [comment]
@hhniao FYI there's a [grpc proxy](https://github.com/ButterCam/Mediator) similar through charles that you can use if that's what you're looking for!

**Comment by hhniao** [comment]
thanks for your reply,
it is not helpful for me, i cant proxy for grpc auth and drop grpc.
this is my first issue. 
https://github.com/googleads/google-ads-php/issues/897
and then i create issue here.
a few day late i have no way to resolve it. 

i have change to rest api now. 
https://developers.google.com/google-ads/api/rest/overview?hl=zh-cn
my work almost finish
