### ISSUE TITLE
pollUntilComplete unauthenticated while (successfully) creating glossary

### ISSUE THREAD

**Issue by meyerluk** [googleapis/gax-php#475]
After updating from [v1.20.2 to v1.21.0](https://github.com/googleapis/gax-php/compare/v1.20.2...v1.21.0#diff-a88e790f67676924a3112580db660b0f21e735035ae7b5ab46a0cfa03e8cd1b3L203) i'm getting an unauthenticated response while waiting for `TranslationServiceClient::createGlossary()` to complete (`$response->pollUntilComplete()`):

```
Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential.
```

Simplified version of the code:
```
$translationClient = new \Google\Cloud\Translate\V3\TranslationServiceClient([
    'credentials' => 'path/to/keyfile.json',
]);

$response = $translationClient->createGlossary(
    \Google\Cloud\Translate\V3\TranslationServiceClient::locationName($config['project_id'], $config['location']),
    new \Google\Cloud\Translate\V3\Glossary()
);

$response->pollUntilComplete();

$translationClient->close();
```

Values from `vendor/google/gax/src/GapicClientTrait::buildClientOptions()`

createGlossary:
```
$options['apiEndpoint']                        -> "translate.googleapis.com:443" 
$defaultOptions['apiEndpoint']                 -> "translate.googleapis.com:443"
$options['credentialsConfig']['scopes']        -> undefined
$options['credentialsConfig']['defaultScopes'] -> [ "https://www.googleapis.com/auth/cloud-platform", "https://www.googleapis.com/auth/cloud-translation" ]
```

pollUntilComplete:
```
$options['apiEndpoint']                        -> "translate.googleapis.com:443" 
$defaultOptions['apiEndpoint']                 -> "longrunning.googleapis.com:443"
$options['credentialsConfig']['scopes']        -> undefined
$options['credentialsConfig']['defaultScopes'] -> [ "https://www.googleapis.com/auth/cloud-platform", "https://www.googleapis.com/auth/cloud-translation" ]
```

After adding the "defaultScopes" to the `credentialsConfig` it is working again.
```
$translationClient = new \Google\Cloud\Translate\V3\TranslationServiceClient([
    'credentials' => 'path/to/keyfile.json',
    'credentialsConfig' => [
        'scopes' => TranslationServiceClient::$serviceScopes,
    ],
]);
```

As seen in [this diff](https://github.com/googleapis/gax-php/compare/v1.20.2...v1.21.0#diff-a88e790f67676924a3112580db660b0f21e735035ae7b5ab46a0cfa03e8cd1b3L203), previously the `defaultScopes` were merged into the `scopes` if the endpoint changed.

Do I have to include the scopes from now on or is this a bug?

**Comment by yash30201** [comment]
Hi @meyerluk,

There was an issue https://github.com/googleapis/google-cloud-php/issues/6386 regarding this which got solved on 28th June. This error should go away once you upgrade your gax to latest: `v1.21.1`.
