### ISSUE TITLE
What is the advantage of Jison?

### ISSUE THREAD

**Issue by bshaffer** [googleapis/gax-php#5]
I've been looking at Jison, and it's a very robust library. It seems to me this is overkill for parsing paths from short strings. 

Is there a speed advantage over regex, or is this being used in another way I'm not aware of?

**Comment by michaelbausor** [comment]
Unfortunately I don't have a good answer to this question. The path template implementation was based on the python implementation here:
https://github.com/googleapis/gax-python/blob/master/google/gax/path_template.py
which uses a yacc parser. Jison was the best option I found to be able to recreate this functionality in PHP.

Regex would be one alternative, and another that has been mentioned for other languages is to implement a recursive descent parser.

**Comment by michaelbausor** [comment]
Closing now that Jison has been removed
