### ISSUE TITLE
Error Google\ApiCore\Middleware\RetryMiddleware problem line 179 or 183 

### ISSUE THREAD

**Issue by dilsonbeltran** [googleapis/gax-php#504]
``
Fatal error: Uncaught TypeError: Google\ApiCore\Middleware\RetryMiddleware::Google\ApiCore\Middleware\{closure}(): Argument #1 ($e) must be of type Exception, Error given, called in src/vendor/google/gax/src/Middleware/RetryMiddleware.php on line 109 and defined in src/vendor/google/gax/src/Middleware/RetryMiddleware.php:183
``

I encountered an issue while working on a script to upload offline conversions using the google-ads-php package. The problem arose from not having the bcmath library installed in PHP, which led to an error on line 179 of Google\ApiCore\Middleware\RetryMiddleware. The issue was that the closure was receiving an object of type \Error instead of \Exception. To address this, I modified the closure by adding the following definition: 

``
function (\Exception|\Error $e, array $options): bool { 
``

instead of:

https://github.com/googleapis/gax-php/blob/a7c1ec7b31513c277a39d419b3fe8f09a6ae999d/src/Middleware/RetryMiddleware.php#L179

This adjustment allowed me to identify the actual error. I hope this information proves helpful, and I'm sharing it here for review purposes.

**Comment by bshaffer** [comment]
Since we still support PHP 7.4 (we expect to drop support for 7.4 in early 2024), we cannot use Union Types yet. However, we can use the [`Throwable`](https://www.php.net/manual/en/class.throwable.php) interface to catch both error and exception messages

**Comment by bshaffer** [comment]
The fix for this has been released in https://github.com/googleapis/gax-php/releases/tag/v1.26.0
