### ISSUE TITLE
PHP 8.4 compatibility

### ISSUE THREAD

**Issue by mikkamp** [googleapis/gax-php#595]
Similar to the PR here: https://github.com/googleapis/google-auth-library-php/pull/584

This library also has several places where parameters are defined as null, but the parameter type does not implicitly allow null. Which throws deprecation warnings in PHP 8.4: https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated

Ideally we'd get these changes backported to the latest version that supports PHP 7.4, [version 1.29.1](https://packagist.org/packages/google/gax#v1.29.1)

#### Environment details

  - OS: mixed
  - PHP version: 8.4
  - Package name and version: [google/gax 1.29.1](https://packagist.org/packages/google/gax#v1.29.1)

**Comment by bshaffer** [comment]
Done in https://github.com/googleapis/gax-php/pull/599
