### ISSUE TITLE
Rewrite CallSettings.load to accept config_overrides

### ISSUE THREAD

**Issue by jmuk** [googleapis/gax-php#7]
Based on the discussion in https://github.com/googleapis/gax-python/issues/95, we are going to accept a parameter `config_overrides` to construct_settings, and retire `retrying_overrides`.

`config_overrides` is in the same structure as `client_config` is, and expected to be supplied from the API users to override the config. Typically, I expect that users will copy the default JSON config file and modify it and pass it.

The returned config has to fall back to the default config, so the `config_overrides` can be a subset of `client_config`. The new `load` will merge these configs before constructing the config.

See also: https://github.com/googleapis/gax-python/pull/103

**Comment by michaelbausor** [comment]
Closing out old issues. Call settings overrides are handled by the RetrySettings object.
